name: covertcoffee
favicon: null
layout_spectrum: 0.11842700815759599
typography_spectrum: 0.4434333511162549
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9025801690295339
  lightness: 0.5065398246515542
  saturation: 0.9979546465910971
  rhythmicContrast: 0.998692482477054
purpose: []
